CREATE TABLE IF NOT EXISTS cars (
    id INT AUTO_INCREMENT PRIMARY KEY,
    model VARCHAR(255) NOT NULL,
    brand VARCHAR(255) NOT NULL,
    years INT NOT NULL,
    color VARCHAR(10) NOT NULL CHECK (color IN ('RED', 'BLUE', 'BLACK', 'GREEN', 'YELLOW'))
);

